#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

#EXPORTS
export MOZ_DISABLE_PANGO=1

userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

xset +fp /home/twebb/.fonts
# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

xset +fp /usr/share/fonts/local
urxvtd -q -f -o
#xbindkeys
# xrdb -merge ~/.Xresources
xrdb -merge ~/.config/X11/base16-xresources/base16-londontube.dark.xresources
#xrandr --output VGA1 --auto
#unclutter -idle 1 &
#subtle &
#/usr/bin/VBoxClient-all
setxkbmap us colemak &
emacs --daemon &
/home/twebb/.cabal/bin/xmonad > /tmp/xmonad.log &
PID=$!
sleep 1
xrandr --output VBOX0 --above VBOX1 
feh --bg-fill $HOME/.wallpaper/akira.png 
unclutter -idle 1 &
unagi &
#keynav &
#xchainkeys &
#mpd
xset -b
wait $PID
